// Hero Voice — curated motivation engine (Phase 4, curated-first per gaps #14).
// Fully offline: no API, no key, no network. A library of short, warm lines keyed
// by style and slot, with deterministic daily rotation so the whole household sees
// the same line all day. Default style is "bright" (encouraging + a little witty,
// never sarcastic). Warm and Calm are alternatives in Settings.
//
// Copy rules (build plan §9) apply to every line: no blame, no debt, no scoreboard.
// AI variation of this library is a later step (P4); live LLM is P5. This is the base.

export type HeroStyle = 'bright' | 'warm' | 'calm';

export const HERO_STYLES: { key: HeroStyle; label: string; blurb: string }[] = [
  { key: 'bright', label: 'Bright', blurb: 'Encouraging, a little witty' },
  { key: 'warm', label: 'Warm', blurb: 'Gentle and validating' },
  { key: 'calm', label: 'Calm', blurb: 'Quiet and grounded' },
];

type Slot =
  | 'greetMorning' | 'greetAfternoon' | 'greetEvening'
  | 'teamBanner'      // Home Value appreciation card
  | 'invaluable'      // mental-load note
  | 'thanksWins'      // Thanks "this week's wins" intro
  | 'saved';          // Add Task success

const LIB: Record<Slot, Record<HeroStyle, string[]>> = {
  greetMorning: {
    bright: [
      "A fresh day for the home team ☀️",
      "Morning! Small things add up today.",
      "New day, same great team ☀️",
      "Here we go — gently does it.",
      "Morning briefing: home operations are open.",
      "Fresh day, clean slate, tiny missions ahead.",
      "Today’s household plot is ready to unfold.",
      "Coffee, courage and a few useful moves.",
      "Mission control is awake and mildly optimistic.",
      "New day, new chances to keep home humming.",
      "The home team is online.",
      "Bright start. Let’s see what the day brings.",
      "Today’s domestic adventure has officially begun.",
      "Morning status: calm, capable, ready.",
      "Fresh page, soft landing, useful little wins.",
      "The day has entered planning mode.",
      "Home base is ready for action.",
      "Tiny tasks, big impact, excellent opening scene.",
      "A new day at headquarters begins.",
      "Fresh energy, steady pace, no drama required.",
      "The household engine is warming up.",
      "Today’s mission board is standing by.",
      "A quiet start can still be heroic.",
      "Opening credits are rolling. HeroNest is ready.",
    ],
    warm: [
      "Good morning. Whatever you do today counts.",
      "Morning — you carry a lot, and it shows.",
      "A new morning for your home 💛",
      "Good morning. Start gently, one thing at a time.",
      "A new day is here, and you can begin softly.",
      "Morning has arrived. Home can move at a human pace.",
      "Begin where you are. Small things still count.",
      "Today does not need to be perfect.",
      "A gentle start is still a start.",
      "Good morning. Let the day unfold kindly.",
      "There is space for steady progress today.",
      "Start with what feels manageable.",
      "Home begins again, quietly and kindly.",
      "This morning can be simple.",
      "A fresh day, without pressure.",
      "You can take today one step at a time.",
      "Good morning. The little things will matter.",
      "Let the first helpful moment be enough.",
      "A calm start can carry the day.",
      "Today can be built in small pieces.",
      "Good morning. Nothing needs to be rushed.",
      "The day is open. Begin gently.",
      "One kind action can set the tone.",
    ],
    calm: [
      "Morning.",
      "A quiet start to the day.",
      "Morning — one thing at a time.",
      "Good morning.",
      "A new day begins.",
      "Start gently.",
      "Today is open.",
      "One thing at a time.",
      "Begin softly.",
      "Fresh day.",
      "Home is ready.",
      "A quiet start.",
      "Steady does it.",
      "Morning check-in.",
      "Start where you are.",
      "Small steps count.",
      "No rush.",
      "Today can be simple.",
      "Breathe first.",
      "Begin with ease.",
      "Fresh start.",
      "A calm beginning.",
      "Here we go.",
    ],
  },
  greetAfternoon: {
    bright: [
      "Afternoon — keeping the place humming 🙌",
      "Halfway through, doing great.",
      "Afternoon! Every little bit helps.",
      "Afternoon check-in: home operations continue.",
      "Midday status: still in the game.",
      "The day has reached its second act.",
      "A useful move now can shift the whole scene.",
      "Mission control remains politely interested.",
      "Afternoon energy: steady, practical, quietly heroic.",
      "The household plot thickens, but kindly.",
      "Time for a small tactical win.",
      "Midday briefing: one helpful thing is enough.",
      "The home team is still moving.",
      "Afternoon mode: assess, adjust, carry on.",
      "A tiny reset could do wonders.",
      "The day is not over; neither is the teamwork.",
      "Home base is still active.",
      "This is a good moment for one simple move.",
      "Afternoon has entered support mode.",
      "Small domestic manoeuvres remain available.",
      "The mission continues, minus the explosions.",
      "Midday rhythm found, or at least negotiable.",
      "Useful things can still happen from here.",
    ],
    warm: [
      "Good afternoon. Thanks for all you do.",
      "Afternoon — the home runs on this.",
      "Good afternoon. There is still room for small wins.",
      "Midday is a good time to reset gently.",
      "The day is moving. You can move with it.",
      "A small helpful action can still matter.",
      "Good afternoon. Take the next step kindly.",
      "There is no need to do everything at once.",
      "Pause, notice, choose one thing.",
      "The afternoon can be lighter than the morning.",
      "You can still make the day feel easier.",
      "A little support now can help the whole home.",
      "Good afternoon. Keep it simple.",
      "This part of the day deserves patience too.",
      "One useful task can be enough.",
      "The home rhythm can still shift gently.",
      "Take a breath before the next thing.",
      "Afternoon is a good time for a soft reset.",
      "Small care still counts.",
      "There is space to adjust the day.",
      "Good afternoon. You are allowed to pace yourself.",
      "Let the next helpful thing be enough.",
    ],
    calm: [
      "Afternoon.",
      "Steady afternoon.",
      "Afternoon — no rush.",
      "Good afternoon.",
      "Midday check-in.",
      "Keep it simple.",
      "One useful thing.",
      "A gentle reset.",
      "Still time.",
      "Steady progress.",
      "Pause and choose.",
      "Afternoon rhythm.",
      "Small steps.",
      "Carry on gently.",
      "One task at a time.",
      "A quiet moment.",
      "Reset if needed.",
      "Simple helps.",
      "Take the next step.",
      "Home continues.",
      "No pressure.",
      "Soft reset.",
      "Keep going kindly.",
    ],
  },
  greetEvening: {
    bright: [
      "Evening — winding down, well done 🌙",
      "That was a team effort today 🌙",
      "Evening! The home was well looked after.",
      "Evening briefing: the day is landing.",
      "Home operations are entering soft-close mode.",
      "The final act prefers calm lighting.",
      "Evening status: fewer missions, more kindness.",
      "The day’s credits are getting ready.",
      "Time to lower the volume on the household engine.",
      "Mission control recommends a gentle finish.",
      "Evening mode: tidy what helps, leave what can wait.",
      "The home team is approaching base.",
      "A calm ending is a strong ending.",
      "Final domestic manoeuvres, if useful.",
      "The day is winding down, no heroics required.",
      "Evening has arrived with softer instructions.",
      "Home base is dimming the lights.",
      "Closing scene: warmth, rest and tiny wins.",
      "The last chapter of today can be gentle.",
      "Evening operations favour comfort.",
      "Soft landing ahead for the home team.",
      "The household sequel can wait until tomorrow.",
      "End the day like a professional: kindly.",
    ],
    warm: [
      "Good evening. Today mattered.",
      "Evening — rest is part of the work too 💛",
      "Good evening. Let the day soften now.",
      "The evening can be gentle.",
      "You can close today with kindness.",
      "Not everything needs finishing tonight.",
      "Good evening. Rest belongs here too.",
      "Let the day land softly.",
      "A quiet finish is enough.",
      "The home can settle now.",
      "You have reached the softer part of the day.",
      "Good evening. Take what peace you can.",
      "Some things can wait for tomorrow.",
      "The day deserves a kind ending.",
      "Let the evening carry less.",
      "A small reset may be enough tonight.",
      "Good evening. You can slow down.",
      "Rest is part of keeping home running.",
      "The day can close without perfection.",
      "Let tonight be lighter.",
      "One gentle thing is enough.",
      "You are allowed to finish softly.",
    ],
    calm: [
      "Evening.",
      "A calm close to the day 🌙",
      "Evening — time to ease off.",
      "Good evening.",
      "Let today land.",
      "Slow down.",
      "Soft finish.",
      "Rest matters.",
      "Evening check-in.",
      "No rush now.",
      "Close gently.",
      "Let it settle.",
      "Enough for today.",
      "Quiet ending.",
      "Breathe out.",
      "Tomorrow can wait.",
      "Evening mode.",
      "A softer pace.",
      "Rest belongs here.",
      "Gentle close.",
      "The day is ending.",
      "Settle in.",
      "You can pause.",
    ],
  },
  teamBanner: {
    bright: [
      "Look at this team go 💛",
      "What a team you're building.",
      "Teamwork, made visible.",
      "Small shifts, big impact 💛",
      "The home crew showed up this week. Strong operations all round.",
      "A proper team effort: tasks moved, value created, home kept running.",
      "This week had logistics, teamwork and a surprising amount of hero energy.",
      "Household mission complete enough to earn applause.",
      "The family operation stayed on course. Nicely played.",
      "Teamwork spotted. The home base appreciates it.",
      "Different tasks, same mission: keeping home running.",
      "This week’s home crew delivered.",
      "Domestic operations report: useful moves across the board.",
      "The team kept the home story moving.",
      "HeroNest notes a strong collective performance.",
      "The week had chores, care and quiet victories.",
      "Your home team created real momentum this week.",
      "This was not magic. It was teamwork.",
      "The family crew handled the week with style.",
      "Small tasks combined into one solid team effort.",
      "Home base remained operational thanks to everyone’s contributions.",
      "A week of useful moves, shared effort and real home value.",
      "The household squad has been quietly impressive.",
      "Teamwork level: very much alive.",
    ],
    warm: [
      "Every contribution here counts.",
      "You're building a more balanced home 💛",
      "See the work. Share the load.",
      "This week, your family helped keep home moving together.",
      "Every contribution helped shape the week at home.",
      "Small acts of care added up across the household.",
      "Your home team created value together this week.",
      "This week shows how much family work matters.",
      "Everyone’s help became part of the bigger picture.",
      "The home ran on shared care and useful moments.",
      "This week was built from many small contributions.",
      "Together, your family helped home feel supported.",
      "The work of home became visible this week.",
      "Each contribution helped carry the household rhythm.",
      "Your family created something valuable together.",
      "This week’s home work deserves appreciation.",
      "The little things added up beautifully.",
      "Home was supported by many helpful moments.",
      "This week, teamwork showed up in practical ways.",
      "Every task helped the home feel more cared for.",
      "Your family’s effort is worth noticing.",
      "Shared work made the week lighter.",
      "Together, you kept home going.",
    ],
    calm: [
      "A picture of this week at home.",
      "The week, gently summarised.",
      "This week at home.",
      "A week of shared effort.",
      "Teamwork noticed.",
      "Home work made visible.",
      "A steady week together.",
      "Contributions counted.",
      "Shared care recorded.",
      "The home team helped.",
      "A useful week.",
      "Together, you contributed.",
      "Home value created.",
      "Small efforts added up.",
      "Family work recognised.",
      "A week supported by teamwork.",
      "Everyone’s help mattered.",
      "The home kept moving.",
      "Shared work, gently noted.",
      "Team effort recorded.",
      "A calm look at the week.",
      "Home support recognised.",
      "Useful contributions, together.",
    ],
  },
  invaluable: {
    bright: [
      "Some of this is simply priceless 💛",
      "Not everything fits a number — and that\\u2019s the good part 💛",
      "The unmeasurable bits? Those matter most.",
      "Emotional logistics handled. The market would call it support; home calls it love.",
      "Some work gets priced. This one gets remembered.",
      "Care delivered, calm restored, invisible work very much visible.",
      "The spreadsheet tried to price this and quietly gave up.",
      "Not every task leaves a clean room. Some leave a calmer heart.",
      "That was care, diplomacy and patience in one tidy package.",
      "Feelings supported, household weather improved. Proper invisible work.",
      "This one is part care, part coaching, part quiet magic.",
      "You kept the human side of home running.",
      "The market has rates. This has meaning.",
      "Emotional support logged. Real value: comfortably beyond maths.",
      "Some work is measured in minutes; this one in steadiness.",
      "You handled the bit nobody sees but everyone feels.",
      "Tiny storm managed. Home atmosphere upgraded.",
      "That was emotional infrastructure, not just a moment.",
      "Care work recorded. The app can count time, not tenderness.",
      "This was support with no invoice and plenty of heart.",
      "A little therapy, a little patience, a lot of home.",
      "You made space for someone’s feelings. That counts.",
      "Invisible work spotted. The quiet kind that holds everything together.",
      "Not glamorous, not loud, absolutely essential.",
      "You kept someone steady. That is proper home value.",
      "This task came with feelings attached. Nicely handled.",
      "Home value estimated. Real value: not available in shops.",
      "You did the kind of work no robot should be trusted with.",
    ],
    warm: [
      "Some work can be estimated. Some can only be appreciated 💛",
      "The care behind this is beyond value 💛",
      "You carried something invisible today. That matters.",
      "This was care work, and it deserves to be seen.",
      "You helped someone feel supported. That is real work.",
      "Not all home work can be measured, but it can be appreciated.",
      "You gave patience, attention and care today.",
      "This work may be quiet, but it is deeply valuable.",
      "You noticed what needed emotional care and showed up for it.",
      "Some work supports the house; this supported the people in it.",
      "You made home feel safer for someone today.",
      "This was one of the invisible things that keeps family life steady.",
      "You offered calm when it was needed.",
      "You helped carry the emotional weight today.",
      "This kind of care is hard to measure and easy to miss.",
      "You gave time to something that really matters.",
      "You supported the part of home that cannot be tidied away.",
      "That was kindness in action.",
      "You helped make the day softer for someone.",
      "This was not small. It was care.",
      "You gave attention where it was needed most.",
      "You helped hold the family rhythm today.",
      "Some work is quiet because it is personal.",
      "You gave someone a steadier moment.",
      "This kind of support is worth noticing.",
      "You did something meaningful, even if it was not visible.",
      "You helped home feel more human today.",
    ],
    calm: [
      "Some of this is simply invaluable.",
      "Not all of it has a number — and need not.",
      "This work is valuable beyond measure.",
      "Care work logged.",
      "Invisible support noticed.",
      "This mattered.",
      "Some work cannot be fully priced.",
      "Emotional support recorded.",
      "Quiet work, real impact.",
      "Care given.",
      "This was meaningful.",
      "The value here is deeper than money.",
      "Mental load recognised.",
      "Support work counted.",
      "This deserves appreciation.",
      "Real care, real work.",
      "A steadying moment logged.",
      "Invisible work made visible.",
      "This helped someone.",
      "Care is part of home.",
      "This work holds things together.",
      "Not everything valuable is visible.",
      "Support given, gently noted.",
      "The human work counts.",
      "This was important.",
      "A quiet contribution recorded.",
      "Some value is simply invaluable.",
    ],
  },
  thanksWins: {
    bright: ['Look back at the good stuff 💛', 'Wins worth a smile this week.', 'The thank-yous add up 💛'],
    warm: ['Moments worth appreciating this week.', 'Kindness, remembered 💛'],
    calm: ["This week's appreciation.", 'A few good moments.'],
  },
  saved: {
    bright: [
      "Logged — nice one 💛",
      "Got it. That counts!",
      "Noted — every bit helps 💛",
      "Done. The team thanks you 🙌",
      "Logged. The household operation continues.",
      "Sorted. The task has officially left the building.",
      "Saved. Domestic progress quietly applauds.",
      "Captured. The invisible just became visible.",
      "Done and logged. A tidy little win.",
      "Recorded. Home value has entered the chat.",
      "Task saved. The house nods respectfully.",
      "Logged nicely. Small move, real impact.",
      "Saved. One more piece of home handled.",
      "Noted. The task has met its paperwork.",
      "Captured. The day looks slightly more heroic.",
      "Logged. Future-you has evidence.",
      "Saved. The home machine keeps humming.",
      "Task recorded. Order has gained a point.",
      "Handled and logged. Very civilised.",
      "Logged. The chore has been formally witnessed.",
      "Saved. The little things are adding up.",
      "Task logged. Household history updated.",
      "Recorded. The work no longer disappears.",
      "Logged. That one counts.",
      "Saved. The home ledger salutes you.",
      "Task secured. Onwards.",
      "Captured. Quiet effort, now visible.",
      "Logged. Domestic operations remain under control.",
      "Saved. Another small victory for the home team.",
      "The nest is running smoother. Nicely done.",
      "Small task, warmer nest, solid move.",
      "Nest operations continue with quiet style.",
      "The home crew handled that one beautifully.",
      "Shared effort logged. The nest approves.",
    ],
    warm: [
      "Logged — thank you 💛",
      "Noted. That work is seen.",
      "Got it — it all matters 💛",
      "Saved. Thank you for helping your home.",
      "Logged. Every contribution counts.",
      "Saved. That made a difference.",
      "Recorded. Your effort is visible now.",
      "Logged. Thank you for doing your part.",
      "Saved. Small tasks help the whole home.",
      "That is logged. It matters.",
      "Saved. Another contribution recognised.",
      "Logged. Thank you for keeping things moving.",
      "Recorded. This helped your family today.",
      "Saved. You added something valuable.",
      "Logged. The little things deserve notice.",
      "Saved. That was a real contribution.",
      "Recorded. Home work recognised.",
      "Logged. Thank you for showing up.",
      "Saved. One helpful moment captured.",
      "Recorded. Your effort did not disappear.",
      "Logged. This is part of what keeps home running.",
      "Saved. Thank you for the care behind it.",
      "Logged. Another quiet win for the home.",
      "Recorded. That helped more than it may seem.",
      "Saved. This contribution is counted.",
      "Logged. Thank you for making home work.",
      "Recorded. A useful thing, now visible.",
      "Saved. That was worth noticing.",
      "You helped make the nest feel cared for.",
      "This small action supported the whole home.",
      "A warmer nest is built from moments like this.",
      "That helped the family rhythm today.",
      "Your care became part of the home.",
    ],
    calm: [
      "Logged.",
      "Noted.",
      "Saved.",
      "Task recorded.",
      "Done.",
      "Added.",
      "Recorded.",
      "Contribution saved.",
      "Task logged.",
      "Home work saved.",
      "Entry added.",
      "Captured.",
      "Saved successfully.",
      "Logged successfully.",
      "Contribution recorded.",
      "That is saved.",
      "Task added.",
      "Work logged.",
      "Entry saved.",
      "Updated.",
      "This is recorded.",
      "Added to today.",
      "Saved to HeroNest.",
      "Task captured.",
      "All set.",
    ],
  },
};

function dayIndex(): number {
  return Math.floor(Date.now() / 86400000);
}

// Deterministic per-day pick (stable for the whole household all day).
export function heroLine(slot: Slot, style: HeroStyle): string {
  const lines = LIB[slot][style];
  return lines[dayIndex() % lines.length];
}

// Random pick for transient moments (e.g. save toasts), avoids feeling robotic.
export function heroLineRandom(slot: Slot, style: HeroStyle): string {
  const lines = LIB[slot][style];
  return lines[Math.floor(Math.random() * lines.length)];
}

export function heroGreeting(style: HeroStyle): string {
  const h = new Date().getHours();
  const slot: Slot = h < 12 ? 'greetMorning' : h < 18 ? 'greetAfternoon' : 'greetEvening';
  return heroLine(slot, style);
}
