// UX copy — mirrors Phase0_Copy_Library.md. No user-facing string ships outside this file.
// Banned phrases are linted in CI (see repo README). Keep this file boring and kind.

export const copy = {
  onboarding: {
    welcomeTitle: 'Welcome to HeroNest',
    welcomeSub: 'See the work. Share the load.',
    createHousehold: "Let's set up your home",
    householdHint: 'The Khan family · Flat 7 crew · whatever feels like you',
    yourName: "What's your name?",
    addPartner: 'Add another adult (optional — they can join later by invite)',
    currencyTitle: 'Your currency',
    valueIntro:
      'HeroNest can estimate the value of household work — a way to make invisible effort visible. You can hide it anytime in Settings.',
    startCta: 'Create our home',
    firstTaskPrompt: 'Log your first task — even small things count.',
  },
  today: {
    greetingMorning: (name: string) => `Good morning, ${name} ☀️`,
    greetingAfternoon: (name: string) => `Good afternoon, ${name}`,
    greetingEvening: (name: string) => `Good evening, ${name} 🌙`,
    statTasks: "Today's tasks",
    statTime: 'Time spent',
    statTimeSub: 'so far today',
    statValue: 'Home value today',
    statValueSub: 'created',
    // Rotating daily lines (deterministic by day, time-of-day aware) — a curated
    // mini-precursor of Hero Voice (Phase 4). Every line passes the Section 9 lint.
    dailyLines: {
      morning: [
        'A new day at home — small things count today.',
        'Morning! One thing at a time, together.',
        'Whatever today brings, it counts here.',
        'Small starts make good days.',
        'A calm start — the little jobs matter too.',
        'Today is a team sport 💛',
      ],
      afternoon: [
        'Midday already — everything so far counted.',
        'A good afternoon for one small thing.',
        'The day is rolling — nice work keeping it going.',
        'Afternoon check-in: it all adds up.',
      ],
      evening: [
        'Evenings count too — gently does it.',
        'Winding down? Whatever got done today mattered.',
        'The quiet end of the day — well held.',
        'Rest is part of running a home, too.',
      ],
    },
    weekSoFarHeader: 'This week so far',
    weekSoFarSub: 'It all adds up 💛',
    weekSoFarCta: 'See your week →',
    affirmTitle: 'Small shifts. Big impact.',
    affirmSub: 'Thanks for showing up for the team.',
    addTaskSub: 'Even a 5-minute task counts',
    emptyToday: 'Nothing logged yet today — even a 5-minute task counts.',
    addTaskCta: 'Add task',
  },
  homeValue: {
    title: 'Home Value',
    empty: 'Once your week has a few tasks, you\'ll see how your family shares the load here.',
    teamTitle: 'Great team 💛',
    teamBody: (hours: string, people: number) =>
      `Together your home took ${hours} of care this week, across ${people} of you. Every bit counted.`,
    sharingTitle: 'How you shared the load',
    donutSub: 'this week',
    valueTitle: 'Value created',
    valueNote: 'Estimated where it can be — and some of it is simply invaluable 💛',
    planTitle: 'Looking at next week',
    rebalance: (cat: string) =>
      `${cat} took the most time this week. Would it help to share one of next week\'s, together?`,
    planCta: 'Plan next week together',
    planSoon: 'Shared planning tools are arriving soon — for now, a chat over coffee works wonders 💛',
  },
  thanks: {
    title: 'Thanks',
    soloHint: 'Once your family joins, you can send a little appreciation here.',
    whoPrompt: 'Who would you like to thank?',
    forPrompt: 'For anything in particular? (optional)',
    notePlaceholder: 'Add a few words (optional)',
    sendCta: 'Send thanks 💛',
    sentToast: (name: string) => `Thanks sent to ${name} 💛`,
    winsTitle: 'This week\'s wins',
    winsEmpty: 'Send your first thanks — small words go a long way.',
    winLine: (from: string, to: string) => `${from} thanked ${to}`,
    winGeneric: 'for helping the team',
  },
  quickLog: {
    title: 'Quick Log',
    sub: "Tell HeroNest what happened. We'll turn it into tasks.",
    // Add Task entry-point pill (Jun 2026 design pass): a real button, not a text link
    entryTitle: 'Tell HeroNest what you did',
    entryHint: "We'll turn your words into tasks ✨",
    // P4b in-app mic
    micLabel: 'Speak your tasks',
    micListening: 'Listening… tap the mic when you\'re done',
    micDenied: 'HeroNest needs microphone access for voice — you can switch it on in your phone settings. Typing works too.',
    micTrouble: "Couldn't quite hear that — give it another go, or just type it.",
    placeholder: 'e.g. I packed lunches, drove the kids to football, and ordered groceries…',
    parseCta: 'Turn it into tasks',
    parsing: 'Reading…',
    unreachable: "Couldn't reach the helper right now — you can still add tasks the usual way.",
    found: (n: number) => `Found ${n} ${n === 1 ? 'task' : 'tasks'} — does this look right?`,
    none: 'No household tasks found in that — try describing what you did.',
    saveAll: (n: number) => `Save ${n === 1 ? 'it' : `all ${n}`}`,
    editHint: 'You can fine-tune any task afterwards from Today.',
  },
  plan: {
    title: "Today's plan",
    empty: 'Nothing planned yet — add something the team can pick up.',
    open: 'Open — anyone can take it',
    takenBy: (name: string) => `Taken by ${name}`,
    claimCta: "I'll do it",
    doneCta: 'Done ✓',
    composerCta: '＋ Plan something for today',
    titleHint: 'Add a short note (optional)',
    anyone: 'Anyone',
    repeatLabels: { none: 'Just today', daily: 'Every day', weekly: 'Weekly' } as Record<string, string>,
    repeatBadge: { daily: 'daily', weekly: 'weekly' } as Record<string, string>,
    addCta: 'Add to plan',
  },
  notify: {
    // Exactly two notification types exist (#61). No habit nudges, ever.
    cardTitle: 'Notifications',
    cardSub: "Just two, both optional. HeroNest never nags.",
    thanksLabel: 'When someone sends me thanks 💛',
    digestLabel: 'Weekly summary (Sunday evening)',
    digestTitle: 'HeroNest',
    digestBody: "Your family's week is ready 💛",
  },
  family: {
    title: 'Your family',
    youSuffix: ' (you)',
    kidModeCta: 'Kids Mode →',
    openKid: (name: string) => `Open ${name}'s Kids Mode`,
  },
  kids: {
    // §10: effort, consistency, confidence, shared wins. Never percentages,
    // money, or member comparisons. Every line passes copy-lint.
    greeting: (name: string) => `Hi, ${name}!`,
    // State-aware greeting (Witty_Message_style_guidance: context boosters;
    // §10: no judgement either way). Nothing done yet -> mission-ahead energy,
    // something done -> present-tense praise. Rotates daily like Hero Voice.
    greetingSubFresh: [
      "A great mission awaits you today! 🚀",
      "Your missions are ready for you ⭐",
      "A brand-new hero day begins ✨",
      "Your missions are ready! ⭐",
      "A new hero day begins!",
      "Today’s quests are waiting!",
      "Ready for a little mission?",
      "Your home team needs you!",
      "Let’s start with one small win!",
      "Hero mode is ready!",
      "Pick a mission and shine!",
      "Today has hero points waiting!",
      "Small helps make big magic!",
      "Your first mission is calling!",
      "Time for a helpful adventure!",
      "Let’s make home sparkle!",
      "One mission can start the fun!",
      "Your hero list is ready!",
      "Choose a task, little legend!",
      "The home team is cheering!",
      "Ready to help your crew?",
      "A fresh mission day is here!",
      "Let’s find your first win!",
      "Your badge journey continues!",
      "Tiny task, big hero energy!",
      "Today’s mission board is open!",
      "Your helpful powers are ready!",
      "Let’s do one kind thing!",
    ],
    greetingSubActive: [
      "You're doing amazing! 💛",
      "You're on a roll today! 🔥",
      "What a hero! ⭐",
      "You’re helping already! ⭐",
      "Great work today!",
      "Your hero points are growing!",
      "You’re on a helpful roll!",
      "Home team power is rising!",
      "You’ve made a great start!",
      "Your missions are looking good!",
      "You’re doing brilliant helping!",
      "That help really counts!",
      "You’re building a hero streak!",
      "Your home team noticed!",
      "Helpful energy is strong today!",
      "You’re making home better!",
      "Nice helping, little hero!",
      "You’ve already earned a win!",
      "Your tasks are flying!",
      "You’re doing amazing today!",
      "Kind help spotted!",
      "Your mission board is moving!",
      "You’re helping like a champ!",
      "HeroNest is impressed!",
      "Your good work is showing!",
      "You’re a true helper today!",
      "Your team is lucky!",
      "Keep going, hero!",
    ],
    statMissions: "Today's missions",
    statMissionsSub: 'to go!',
    statPoints: 'Hero points',
    statStreak: 'Streak',
    statStreakSub: 'days',
    statPocket: 'Pocket money',
    statPocketSub: 'earned',
    missionsTitle: "Today's missions",
    missionsEmpty: 'No missions yet — tap "I helped!" when you do something kind for the team.',
    missionDone: 'Mission done',
    badgesTitle: 'Your badges',
    badgeKitchen: 'Kitchen Helper',
    badgePet: 'Pet Pal',
    badgeLaundry: 'Laundry Hero',
    badgeTidy: 'Tidy Star',
    badgeTeam: 'Team Player',
    badgeNext: 'Next up!',
    badgeProgress: (n: number, need: number) => `${n} of ${need}`,
    starters: ['Make my bed', 'Feed the pet', 'Clear the table', 'Tidy my room'],
    affirmTitle: (n: number) => n > 0 ? `You helped ${n} ${n === 1 ? 'time' : 'times'} this week!` : 'Ready to help the team?',
    affirmSub: "Keep it up, you're a true hero! 💪",
    helpedCta: 'I helped!',
    helpPrompt: 'What did you help with?',
    earnedTemplates: [
      "+{points} hero points! ⭐",
      "You earned +{points} points! ⭐",
      "Mission complete: +{points} points!",
      "Great helping: +{points} points!",
      "+{points} points for your hero work!",
      "Task done: +{points} points!",
      "You did it: +{points} points!",
      "Nice work: +{points} points!",
      "+{points} points unlocked!",
      "Hero win: +{points} points!",
      "Big help: +{points} points!",
      "Mission win: +{points} points!",
      "Sparkly work: +{points} points! ✨",
      "+{points} points for helping!",
      "Home team thanks you: +{points}!",
      "You helped: +{points} points!",
      "Brilliant job: +{points} points!",
      "Kind task done: +{points} points!",
      "Helpful hero: +{points} points!",
      "Quest complete: +{points} points!",
      "Teamwork win: +{points} points!",
      "+{points} points added!",
      "Hero board updated: +{points}!",
      "You smashed it: +{points} points!",
      "Another win: +{points} points!",
      "Nest mission complete! ⭐",
      "Your nest crew says thank you!",
      "Small helper, big nest magic!",
      "You helped the nest today!",
      "HeroNest is cheering for you!",
    ],
    earned: (pts: number) => {
      const t = copy.kids.earnedTemplates[Math.floor(Math.random() * copy.kids.earnedTemplates.length)];
      return t.replace('{points}', String(pts));
    },
    allDone: [
      "All missions complete! ⭐",
      "You finished everything today!",
      "Full hero day complete!",
      "Your mission board is clear!",
      "Amazing work, nest hero!",
      "Every task is done!",
      "You helped all the way!",
      "Big high-five for you!",
      "Today’s quests are complete!",
      "You did the whole list!",
      "Home team celebration time!",
      "All done, little legend!",
      "Mission day completed!",
      "You cleared the board!",
      "That is full hero power!",
      "Every mission is checked!",
      "Your help really shone today!",
      "Brilliant finish!",
      "You completed the home quest!",
      "All tasks done and dusted!",
      "Your hero work is complete!",
      "Everything is ticked off!",
      "Super helping day complete!",
      "You finished like a champ!",
      "HeroNest gives a huge cheer!",
    ],
    streakTemplates: [
      "{days} days of helping! ⭐",
      "Your streak is {days} days!",
      "{days}-day hero streak!",
      "You kept going for {days} days!",
      "Amazing {days}-day streak!",
      "Your helpful streak is growing!",
      "{days} days of kind help!",
      "Hero habit unlocked: {days} days!",
      "You turned up {days} days in a row!",
      "That is {days} days of effort!",
      "Your streak badge is shining!",
      "{days} days of teamwork!",
      "You are building a great habit!",
      "Helpful hero, {days} days strong!",
      "Your streak is looking brilliant!",
      "{days} days of nest hero work!",
      "You kept your streak alive!",
      "That is real consistency!",
      "{days} days, nicely done!",
      "Your mission streak continues!",
      "You are on a steady roll!",
      "Great helping, day after day!",
      "Your streak has levelled up!",
      "HeroNest sees your consistency!",
      "Keep that hero streak glowing!",
    ],
    streakLine: (days: number) => {
      const t = copy.kids.streakTemplates[days % copy.kids.streakTemplates.length];
      return t.replace('{days}', String(days));
    },
    badgeTemplates: [
      "You unlocked {badge}! ⭐",
      "{badge} badge earned!",
      "New badge: {badge}!",
      "Hooray! {badge} is yours!",
      "{badge} added to your collection!",
      "You earned the {badge} badge!",
      "Badge unlocked: {badge}!",
      "Your {badge} badge is shining!",
      "Great job earning {badge}!",
      "{badge} looks good on you!",
      "A new badge has arrived!",
      "Your badge board grew!",
      "Hero badge unlocked: {badge}!",
      "You collected {badge}!",
      "Mission reward: {badge}!",
      "{badge} is now yours!",
      "Badge celebration time!",
      "You added {badge} today!",
      "Your hero collection is growing!",
      "Sparkly new {badge} badge!",
      "You did it: {badge}!",
      "{badge} joined your badges!",
      "HeroNest badge unlocked!",
      "A brilliant badge win!",
      "You earned something special!",
    ],
    badgeLine: (badge: string) => {
      const t = copy.kids.badgeTemplates[Math.floor(Math.random() * copy.kids.badgeTemplates.length)];
      return t.replace('{badge}', badge);
    },
    exitHint: 'Grown-ups: hold to exit',
    switchTitle: 'Whose turn?',
  },
  avatars: {
    // Hero titles (Avatar_guidance doc): playful identity, never rank or judgement
    titles: {
      maria: 'The Calendar Keeper',
      james: 'The Fixer',
      dad: 'The Calm Commander',
      hero: 'The Planner',
      teen: 'The Snack Captain',
      boy: 'Homework Helper',
      liam: 'Mini Hero',
      ava: 'Sock Detective',
      girl: 'Toy Tamer',
      dog: 'Playful Dog',
      sol: 'The Listener',
      rosa: 'The Laundry Legend',
      nana: 'The One Who Remembers',
      amara: 'The Crisis Manager',
      noor: 'The Organiser Hero',
      omar: 'The School Run Hero',
      baz: 'The Bin Boss',
      papa: 'The Grocery Hero',
      kira: 'The Clean-Up Hero',
      mei: 'The Homework Hawk',
      tom: 'The Dinner Defender',
      zuri: 'Plate Champion',
      lily: 'Sock Finder',
      finn: 'Rubbish Ranger',
      kai: 'Tidy Tiger',
      remy: 'Table-Setting Titan',
      fox: 'Brave Fox',
      owl: 'Wise Owl',
      bear: 'Cozy Bear',
      bee: 'Busy Bee',
      puppy: 'Loyal Puppy',
      unicorn: 'Magical Unicorn',
      rabbit: 'Gentle Rabbit',
      cat: 'Curious Cat',
      hedgehog: 'Happy Hedgehog',
    } as Record<string, string>,
    fallbackTitle: 'Household Hero',
  },
  photo: {
    title: 'Update photo',
    camera: 'Take a photo',
    library: 'Choose from library',
    menuTitle: 'Your avatar',
    heroOption: 'Pick a hero face',
    heroTitle: 'Pick your hero face',
    heroSub: 'A little you — no photo needed 💛',
    cancel: 'Cancel',
  },
  addTask: {
    screenTitle: 'Add a task',
    whatPrompt: 'What did you do?',
    titleHint: 'Add a detail (optional)',
    durationPrompt: 'How long did it take?',
    custom: 'Custom',
    whoPrompt: 'Who did it?',
    valuePreview: (cur: string, n: number) => `Estimated value: ${cur}${n}`,
    valueInvaluable: 'Real value: invaluable 💛',
    valuePreviewSub: 'Based on your household rates',
    whenPrompt: 'When?',
    dayToday: 'Today',
    dayYesterday: 'Yesterday',
    noteLink: '+ Add a note (just for you)',
    saveCta: 'Add task',
    editTitle: 'Edit task',
    editCta: 'Save changes',
    savedToast: 'Logged 💛',
    savedEdit: 'Updated 💛',
    savedFirstEver: 'First task logged — it all counts from here.',
  },
  comingSoon: {
    homeValueTitle: 'Home Value',
    homeValueBody:
      'See how your family shares the load — by time, category, and value — with a plan-next-week tool. Built as a planning view, never a scoreboard.',
    thanksTitle: 'Thanks',
    thanksBody:
      'One-tap appreciation: send thanks for the work you noticed, and see weekly family wins.',
    togetherNote:
      'These two arrive together in Phase 2 (closed beta) — appreciation always ships alongside comparison, never after it.',
    phaseTag: 'Scheduled: Phase 2 · Weeks 9–14',
  },
  week: {
    header: 'This week at home…',
    heroHours: (h: number, m: number) => `${h}h ${m}m of family work`,
    heroValue: (cur: string, n: number) => `≈ ${cur}${n} estimated value`,
    deltaMore: (x: string) => `${x} more than last week`,
    deltaLess: (x: string) => `${x} less than last week`,
    deltaSame: 'About the same as last week',
    mentalLoadHeader: 'Mental load',
    mentalLoadSub: 'Planning, remembering, and emotional support — real work, often invisible.',
    donutHeader: 'Top categories this week',
    donutCenterSub: 'total',
    donutOther: 'Everything else',
    mentalLoadInvaluable: 'Some work can be estimated. Some can only be appreciated 💛',
    sparseWeek: 'A quieter week on record — log as much or as little as helps.',
  },
  settings: {
    // Kids Mode additions
    addChildCta: '＋ Add a child',
    addChildBusy: 'Setting up their nest…',
    addChildHint: "Their name (no email needed — they share a grown-up's device)",
    addChildSave: 'Create profile',
    addChildOffline: 'Connect to the internet to add a family member.',
    kidBadge: 'Kid',
    openKidMode: 'Open Kids Mode →',
    pocketTitle: 'Pocket money',
    pocketSub: "Optional: turn hero points into pocket money. You're in charge of the rate — and of paying out 💛",
    pocketRate: (cur: string) => `points = ${cur}1`,
    ratesTitle: 'Hourly rates',
    ratesSub: 'Used to estimate the value of household work. Adjust anytime.',
    hideMoneyLabel: 'Hide money everywhere',
    hideMoneySub:
      "Some families prefer hours only. Value disappears from every screen instantly — your data isn't deleted.",
    currencyTitle: 'Currency',
    membersTitle: 'Household members',
    editPhoto: 'Edit photo',
    voiceTitle: 'Hero Voice',
    voiceSub: 'How HeroNest talks to your family. Change it anytime.',
    dataTitle: 'Your data',
    dataSub: 'Your household data belongs to your family — take a copy or remove it any time.',
    exportCta: 'Export household data',
    exportCopiedTitle: 'Export ready',
    exportCopiedBody: 'Your data was copied to the clipboard as JSON.',
    deleteCta: 'Delete household everywhere…',
    deleteConfirm: 'This removes the household for every member, everywhere. Tap again to confirm.',
    metricsTitle: 'Logging speed (dev metric)',
    resetCta: 'Reset local data',
    resetConfirm: 'Tap again to confirm — this clears local demo data on this device only.',
  },
  sync: {
    sendingCode: 'Sending your code…',
    inviteBusy: 'Making your invite…',
    inviteScanHint: 'Scan with a phone camera — or copy the link below',
    inviteShareText: (code: string, url: string) => `Join our HeroNest home! Tap ${url} or use code ${code} (works for 48 hours).`,
    syncing: 'Syncing…',
    verifying: 'Letting you in…',
    working: 'Tucking it into the nest…',
    cardTitle: 'Sync & account',
    introLocal: 'Your data lives on this device. Sign in to back it up and invite your family.',
    emailPrompt: 'Your email',
    sendCode: 'Send sign-in code',
    codeSent: 'Check your email and click the sign-in link — this page will sign in automatically. (If your email shows a 6-digit code, you can enter it below instead.)',
    codePrompt: 'Enter the code',
    verify: 'Sign in',
    uploadPrompt: 'Back up this household and turn on family sync?',
    uploadCta: 'Upload household to cloud',
    inviteCopy: 'Copy code',
    inviteCopied: 'Copied ✓',
    inviteTitle: 'Invite your family',
    inviteCta: 'Create invite code',
    inviteShare: (code: string) =>
      `Join our home on HeroNest 🪺 Open the app, choose "Join with invite", and enter code: ${code} (valid 7 days)`,
    syncNow: 'Sync now',
    lastSync: (when: string) => `Last synced ${when}`,
    pending: (n: number) => `${n} change${n === 1 ? '' : 's'} waiting to sync — safe and will upload automatically.`,
    allSynced: 'Everything is synced.',
    signOut: 'Sign out',
    joinTitle: 'Join with invite',
    joinIntro: 'Someone set up your home already? Sign in, then enter your invite code.',
    inviteCodePrompt: 'Invite code',
    yourNamePrompt: 'Your name (as your family knows you)',
    joinCta: 'Join household',
    signInTab: 'Sign in / Join',
    createTab: 'Create new home',
  },
  errors: {
    generic: "That didn't go through. Your data is safe — try again in a moment.",
  },
};

export const currencySymbol: Record<string, string> = {
  AED: 'AED ', USD: '$', EUR: '€', GBP: '£',
};

// Deterministic daily greeting line: same line for the whole household all day,
// rotates with the calendar, varies by time of day.
export function dailyLine(): string {
  const h = new Date().getHours();
  const period = h < 12 ? 'morning' : h < 18 ? 'afternoon' : 'evening';
  const lines = copy.today.dailyLines[period];
  const day = Math.floor(Date.now() / 86400000);
  return lines[day % lines.length];
}
